# Generated by Django 3.2.6 on 2021-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(max_length=200, null=True, unique=True)),
                ('name_ar', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
    ]
