# Generated by Django 3.2.6 on 2021-08-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(max_length=200, null=True, unique=True)),
                ('name_ar', models.CharField(max_length=200, null=True, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.country')),
            ],
        ),
    ]
