# Generated by Django 3.2.6 on 2021-08-12 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.city')),
            ],
        ),
    ]
