# Generated by Django 3.1.3 on 2020-11-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20201121_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together=set(),
        ),
    ]
